__author__ = 'goldenxradian'

from bs4 import BeautifulSoup

def makeSoup():

    html_doc = """
<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""
    soup = BeautifulSoup(html_doc)

    return soup


def goJQueryBasics(soup):

    # Basic nagivation:
    print "Here are some basic navigation tips: "
    print soup.title
    print soup.name


def goJQueryChangeTags(soup):

    print "\nWhat if you want to change the tags?"
    # Getting the tags from the XML/HTML document
    print "soup.b: ", soup.b            # This is the first initial tag surrounded by <b>
    tag = soup.b
    print "Tag: ", tag                  # This is the full tag that was extracted
    print "tag.name: ", tag.name        # The letter(s) inside the <>
    print "tag.string: ", tag.string    # The actual string inside the tags
    # Any tag name changes are reflected in any HTML markup generated by BeautifulSoup
    tag.name ="Blockquote"
    print tag                           #Notice that the outer tags actually changed

    # The tag is generally a dictionary, so you can add/remove/modify a tag's attributes
    tag['class'] = 'verybold'
    tag['id'] = 1
    print "\nAdding class and ID tags: "
    print tag
    print "\n Deleting the ID tag: "
    del tag['id']
    print tag


def main():

    # Make sure you have the two parenthesis! When in doubt, just add it in case.
    soup = makeSoup()
    goJQueryBasics(soup)
    goJQueryChangeTags(soup)


if __name__ == "__main__":
    main()
